In [37]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder

# One Hot encoding

In [ ]:
encoder = OneHotEncoder()

In [6]:
color = [
    "red",
    "yellow",
    "green",
    "red",
    "green",
    "yellow"
]

In [24]:
data =pd.DataFrame(color,columns=["color"])
encoded = encoder.fit_transform(data)
modified_data = encoded.toarray()
k = pd.DataFrame(modified_data,columns=encoder.get_feature_names_out())
k

   color_green  color_red  color_yellow
0          0.0        1.0           0.0
1          0.0        0.0           1.0
2          1.0        0.0           0.0
3          0.0        1.0           0.0
4          1.0        0.0           0.0
5          0.0        0.0           1.0

In [29]:
final_data = pd.concat([data,k],axis=1)
final_data

    color  color_green  color_red  color_yellow
0     red          0.0        1.0           0.0
1  yellow          0.0        0.0           1.0
2   green          1.0        0.0           0.0
3     red          0.0        1.0           0.0
4   green          1.0        0.0           0.0
5  yellow          0.0        0.0           1.0

# LableEncoder

In [36]:
encoder = LabelEncoder()
pd_data =encoder.fit_transform(data["color"])
print(pd_data)

[1 2 0 1 0 2]

In [44]:
demodata = {
    "size": ["Small", "Large", "Medium", "Small"]
}

data = pd.DataFrame(demodata)

encoder = OrdinalEncoder(categories=[["Small", "Medium", "Large"]])
data_mm = encoder.fit_transform(data[["size"]])
data_mm

modified = pd.DataFrame(data_mm,columns=["order"])
final_data =pd.concat([data,modified],axis=1)
final_data

     size  order
0   Small    0.0
1   Large    2.0
2  Medium    1.0
3   Small    0.0